package com.nt.domain;
// Generated Jan 8, 2017 10:54:58 AM by Hibernate Tools 5.1.0.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Account generated by hbm2java
 */
@Entity
@Table(name = "ACCOUNT", schema = "SYSTEM")
public class Account implements java.io.Serializable {

	private int acno;
	private String holder;
	private BigDecimal balance;

	public Account() {
	}

	public Account(int acno) {
		this.acno = acno;
	}

	public Account(int acno, String holder, BigDecimal balance) {
		this.acno = acno;
		this.holder = holder;
		this.balance = balance;
	}

	@Id

	@Column(name = "ACNO", unique = true, nullable = false, precision = 5, scale = 0)
	public int getAcno() {
		return this.acno;
	}

	public void setAcno(int acno) {
		this.acno = acno;
	}

	@Column(name = "HOLDER", length = 20)
	public String getHolder() {
		return this.holder;
	}

	public void setHolder(String holder) {
		this.holder = holder;
	}

	@Column(name = "BALANCE", precision = 10)
	public BigDecimal getBalance() {
		return this.balance;
	}

	public void setBalance(BigDecimal balance) {
		this.balance = balance;
	}

}
